export const defaultRoles = [
  {
    id: "doppelganger",
    roleGroupId: "doppelganger",
    name: "Kẻ Giả Mạo",
    englishName: "Doppelganger",
    description: "Thức dậy đầu tiên, xem bài của 1 người khác và đóng vai trò của họ.",
    defaultDuration: 15,
    defaultOrder: 1,
    wakesUp: true,
    team: "villager",
    icon: "Copy",
    wakeScript: "Kẻ giả mạo hãy thức dậy. Hãy xem lá bài của một người chơi khác và thực hiện hành động của vai trò đó.",
    sleepScript: "Kẻ giả mạo hãy nhắm mắt lại."
  },
  {
    id: "werewolf",
    roleGroupId: "werewolf",
    name: "Ma Sói",
    englishName: "Werewolf",
    description: "Đồng bọn nhận mặt nhau. Nếu chỉ có 1 sói, được xem 1 lá bài ở giữa.",
    defaultDuration: 15,
    defaultOrder: 2,
    wakesUp: true,
    team: "werewolf",
    icon: "ShieldAlert",
    wakeScript: "Ma sói hãy thức dậy, mở mắt ra và tìm đồng bọn của mình. Nếu bạn là ma sói duy nhất, hãy xem một lá bài ở giữa.",
    sleepScript: "Ma sói hãy nhắm mắt lại."
  },
  {
    id: "minion",
    roleGroupId: "minion",
    name: "Kẻ Phản Bội",
    englishName: "Minion",
    description: "Thức dậy để biết mặt các Ma Sói (Ma Sói giơ ngón tay cái lên).",
    defaultDuration: 10,
    defaultOrder: 3,
    wakesUp: true,
    team: "werewolf",
    icon: "Flame",
    wakeScript: "Kẻ phản bội hãy thức dậy. Ma sói hãy giơ ngón tay cái lên để kẻ phản bội biết bạn là ai.",
    sleepScript: "Kẻ phản bội hãy nhắm mắt lại. Ma sói hãy rụt ngón tay cái xuống."
  },
  {
    id: "mason",
    roleGroupId: "mason",
    name: "Thợ Xây",
    englishName: "Mason",
    description: "Các Thợ Xây thức dậy để nhận mặt nhau.",
    defaultDuration: 10,
    defaultOrder: 4,
    wakesUp: true,
    team: "villager",
    icon: "Hammer",
    wakeScript: "Thợ xây hãy thức dậy, mở mắt ra và nhận diện người thợ xây còn lại.",
    sleepScript: "Thợ xây hãy nhắm mắt lại."
  },
  {
    id: "seer",
    roleGroupId: "seer",
    name: "Tiên Tri",
    englishName: "Seer",
    description: "Được xem bài của 1 người khác HOẶC xem 2 bài trong số 3 bài ở giữa.",
    defaultDuration: 15,
    defaultOrder: 5,
    wakesUp: true,
    team: "villager",
    icon: "Eye",
    wakeScript: "Tiên tri hãy thức dậy. Bạn có thể xem bài của một người chơi khác, hoặc xem hai lá bài ở giữa.",
    sleepScript: "Tiên tri hãy nhắm mắt lại."
  },
  {
    id: "robber",
    roleGroupId: "robber",
    name: "Kẻ Trộm",
    englishName: "Robber",
    description: "Được tráo bài của mình với 1 người chơi khác và xem lá bài mới đó.",
    defaultDuration: 15,
    defaultOrder: 6,
    wakesUp: true,
    team: "villager",
    icon: "UserMinus",
    wakeScript: "Kẻ trộm hãy thức dậy. Bạn có thể tráo bài của mình với một người chơi khác và xem vai trò mới của mình.",
    sleepScript: "Kẻ trộm hãy nhắm mắt lại."
  },
  {
    id: "troublemaker",
    roleGroupId: "troublemaker",
    name: "Kẻ Phá Rối",
    englishName: "Troublemaker",
    description: "Được tráo bài của 2 người chơi khác với nhau mà không được xem bài.",
    defaultDuration: 15,
    defaultOrder: 7,
    wakesUp: true,
    team: "villager",
    icon: "GitCompare",
    wakeScript: "Kẻ phá rối hãy thức dậy. Bạn có thể tráo đổi bài của hai người chơi khác nhau mà không được nhìn vào bài của họ.",
    sleepScript: "Kẻ phá rối hãy nhắm mắt lại."
  },
  {
    id: "drunk",
    roleGroupId: "drunk",
    name: "Chàng Say",
    englishName: "Drunk",
    description: "Tráo bài của mình với 1 trong 3 lá bài ở giữa mà không được xem bài.",
    defaultDuration: 12,
    defaultOrder: 8,
    wakesUp: true,
    team: "villager",
    icon: "Wine",
    wakeScript: "Chàng say hãy thức dậy. Hãy tráo đổi bài của bạn với một trong ba lá bài ở giữa mà không nhìn vào nó.",
    sleepScript: "Chàng say hãy nhắm mắt lại."
  },
  {
    id: "insomniac",
    roleGroupId: "insomniac",
    name: "Kẻ Mất Ngủ",
    englishName: "Insomniac",
    description: "Thức dậy để kiểm tra xem bài của mình có bị thay đổi hay không.",
    defaultDuration: 10,
    defaultOrder: 9,
    wakesUp: true,
    team: "villager",
    icon: "Moon",
    wakeScript: "Kẻ mất ngủ hãy thức dậy. Hãy kiểm tra bài của mình xem có bị thay đổi trong đêm hay không.",
    sleepScript: "Kẻ mất ngủ hãy nhắm mắt lại."
  },
  {
    id: "villager",
    roleGroupId: "villager",
    name: "Dân Thường",
    englishName: "Villager",
    description: "Không thức dậy vào ban đêm. Có nhiệm vụ thảo luận để tìm ra Ma Sói.",
    wakesUp: false,
    team: "villager",
    icon: "User"
  },
  {
    id: "hunter",
    roleGroupId: "hunter",
    name: "Thợ Săn",
    englishName: "Hunter",
    description: "Không thức dậy ban đêm. Nếu bị treo cổ, người thợ săn chọn ai thì người đó cũng chết theo.",
    wakesUp: false,
    team: "villager",
    icon: "Target"
  },
  {
    id: "tanner",
    roleGroupId: "tanner",
    name: "Kẻ Chán Đời",
    englishName: "Tanner",
    description: "Không thức dậy ban đêm. Thắng nếu bị mọi người biểu quyết treo cổ.",
    wakesUp: false,
    team: "tanner",
    icon: "Angry"
  }
];
